version: "3"
services:
  app:
    container_name: upsnap_app
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8000
      - BACKEND_PORT=8001
      - BACKEND_IS_PROXIED=false # set this to true, if you use a reverse proxy
      - DB_TYPE=sqlite # required
      - REDIS_HOST=127.0.0.1 # required (make sure to use the same ip as below)
      - REDIS_PORT=6379 # required (make sure to use the same port as below)
      #- PING_INTERVAL=5 # optional (default: 5 seconds)
      #- DJANGO_SUPERUSER_USER=admin # optional (default: backend login disabled)
      #- DJANGO_SUPERUSER_PASSWORD=admin # optional (default: backend login disabled)
      #- DJANGO_SECRET_KEY=secret # optional (default: randomly generated)
      #- DJANGO_DEBUG=True # optional (default: False)
      #- DJANGO_LANGUAGE_CODE=de # optional (default: en)
      #- DJANGO_TIME_ZONE=Europe/Berlin # optional (default: UTC)
      #- NMAP_ARGS=-sP # optional, set this if your devices need special nmap args so they can be found (default: -sP)
      #- PAGE_TITLE=Custom Title # optional, set a custom page title (default: UpSnap)
    volumes:
      - ./db/:/app/backend/db/
    depends_on:
      redis:
        condition: service_healthy
  redis:
    container_name: upsnap_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --loglevel warning
    healthcheck:
      test: redis-cli ping
      interval: 10s
