version: "3"
services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:3
    network_mode: host
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    # environment:
    #   - TZ=Europe/Berlin
    #   - UPSNAP_INTERVAL=@every 10s
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24
    #   - UPSNAP_WEBSITE_TITLE=Custom name
    # command: ["./upsnap", "serve", "--http", "0.0.0.0:8090"]
