version: "3"
services:
  app:
    container_name: upsnap_app
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8000
      - BACKEND_PORT=8001
      - DB_TYPE=mysql # required
      - REDIS_HOST=127.0.0.1 # required (make sure to use the same ip as below)
      - REDIS_PORT=6379 # required (make sure to use the same port as below)
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=upsnap
      - DB_USER=upsnap
      - DB_PASSWORD=upsnap
      #- PING_INTERVAL=5 # optional (default: 5 seconds)
      #- DJANGO_SUPERUSER_USER=admin # optional (default: backend login disabled)
      #- DJANGO_SUPERUSER_PASSWORD=admin # optional (default: backend login disabled)
      #- DJANGO_SECRET_KEY=secret # optional (default: randomly generated)
      #- DJANGO_DEBUG=True # optional (default: False)
      #- DJANGO_LANGUAGE_CODE=de # optional (default: en)
      #- DJANGO_TIME_ZONE=Europe/Berlin # optional (default: UTC)
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  redis:
    container_name: upsnap_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --loglevel warning
    healthcheck:
      test: redis-cli ping
      interval: 10s
  mysql:
    container_name: upsnap_mysql
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=upsnap
      - MYSQL_USER=upsnap
      - MYSQL_PASSWORD=upsnap
      - MYSQL_ROOT_PASSWORD=upsnap
    cap_add:
      - SYS_NICE
    volumes:
      - upsnap_db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
volumes:
  upsnap_db:
