release:
  # draft: true
  prerelease: auto
before:
  hooks:
    - go mod tidy
builds:
  - binary: upsnap
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/seriousm4x/upsnap/pb.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
archives:
  - format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Go dependencies"
      regexp: '^.*?go-dep(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Npm dependencies"
      regexp: '^.*?npm-dep(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Github Actions"
      regexp: '^.*?gh-action(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Others
      order: 999
